package main

import (
	"database/sql"
	"os"

	_ "github.com/alfynf/simple-blog-api/docs" // docs is generated by Swag CLI
	"github.com/alfynf/simple-blog-api/internal/config"
	"github.com/alfynf/simple-blog-api/internal/handler"
	"github.com/alfynf/simple-blog-api/internal/middleware"
	"github.com/alfynf/simple-blog-api/internal/repository"
	"github.com/alfynf/simple-blog-api/internal/service"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/gin-gonic/gin"
	_ "github.com/lib/pq" // Driver Postgres
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

// @title           Simple Blog API
// @version         1.0
// @description     This is a simple blog API server for creating and managing blog posts and comments.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	// --- Konfigurasi Logger ---
	// Use pretty logging for development
	log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})

	// --- Muat Konfigurasi ---
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatal().Err(err).Msg("failed to load configuration")
	}

	// --- Koneksi Database ---
	connStr := cfg.DBConnectionString()
	db, err := sql.Open("postgres", connStr)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to connect to database")
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Fatal().Err(err).Msg("failed to ping database")
	}
	log.Info().Msg("Database connected successfully")

	// --- Dependency Injection ---
	// 1. Inisialisasi Repositories
	userRepo := repository.NewUserRepository(db)
	postRepo := repository.NewPostRepository(db)
	commentRepo := repository.NewCommentRepository(db)

	// 2. Inisialisasi Services
	userService := service.NewUserService(userRepo, cfg)
	postService := service.NewPostService(postRepo)
	commentService := service.NewCommentService(commentRepo, postRepo)

	// 3. Inisialisasi Handlers
	userHandler := handler.NewUserHandler(userService)
	postHandler := handler.NewPostHandler(postService)
	commentHandler := handler.NewCommentHandler(commentService)

	// --- Router ---
	router := gin.Default()

	// Gunakan middleware logger untuk semua request
	// Gin's default logger will be replaced by this
	router.Use(middleware.Logger())

	// Rute untuk Swagger UI
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Grup routing v1
	apiV1 := router.Group("/api/v1")
	{
		// Rute untuk otentikasi dan registrasi user
		authRoutes := apiV1.Group("/")
		authRoutes.POST("/register", userHandler.Register)
		authRoutes.POST("/login", userHandler.Login)

		// Rute yang memerlukan otentikasi
		protected := apiV1.Group("/")
		protected.Use(middleware.AuthMiddleware(cfg))
		{
			// Posts
			protected.POST("/posts", postHandler.CreatePost)
			protected.PUT("/posts/:id", postHandler.UpdatePost)
			protected.DELETE("/posts/:id", postHandler.DeletePost)

			// Comments
			protected.POST("/posts/:id/comments", commentHandler.CreateComment)
			protected.PUT("/comments/:commentID", commentHandler.UpdateComment)
			protected.DELETE("/comments/:commentID", commentHandler.DeleteComment)
		}

		// Rute publik yang tidak memerlukan otentikasi
		apiV1.GET("/posts/:id", postHandler.GetPost)
		apiV1.GET("/posts/:id/comments", commentHandler.GetCommentsByPost)
	}

	// --- Jalankan Server ---
	log.Info().Msgf("Starting server on :%s", cfg.ServerPort)
	if err := router.Run(":" + cfg.ServerPort); err != nil {
		log.Fatal().Err(err).Msg("failed to run server")
	}
}
